---
dependency:
  name: galaxy
driver:
  name: docker
#lint: ansible-lint
platforms:
  - name: centos-8
    hostname: centos
    image: geerlingguy/docker-centos8-ansible:latest
    privileged: true
    pre_build_image: true
    override_command: false
  - name: debian-11
    hostname: debian
    image: geerlingguy/docker-debian11-ansible:latest
    privileged: true
    pre_build_image: true
    override_command: false
provisioner:
  name: ansible
verifier:
  name: ansible
