---
name: build fakepkg
on: [push]
jobs:
  build:
    name: build fakepkg
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: molecule test
        uses: gofrolist/molecule-action@v2
        with:
          molecule_working_dir: ansible/my_test_role
          molecule_command: test
        env:
          ANSIBLE_FORCE_COLOR: '1'
