---
name: Molecule
on: [push,workflow_dispatch]
jobs:
  build:
    name: Molecule Test
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: molecule test
        uses: gofrolist/molecule-action@v2
        with:
          molecule_args:
          molecule_working_dir: actionstesting/ansible/my_new_role
          molecule_command: test
        env:
          ANSIBLE_FORCE_COLOR: '1'
