name: build fakepkg
on: [push]
jobs:
  build:
    name: build fakepkg
    runs-on: macos-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
        with:
          path: main
      - name: checkout munkipkg
        uses: actions/checkout@v3
        with:
          repository: munki/munki-pkg
          path: munkipkg
      - name: build pkg
        run: munkipkg/munkipkg main/fakepkg
      - name: archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: fakepkg-built
          path: main/fakepkg/build/*.pkg
