name: build fakepkg
on: [push]
jobs:
  build:
    name: build fakepkg
    runs-on: macos-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: checkout munkipkg
        uses: actions/checkout@v3
        with:
          - repository: munki/munki-pkg
