name: date
on: [push]
jobs:
  job1:
    name: job1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: print date
        run: date
  job2:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        name: print date
        run: date
  job3:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        name: print date
        run: Get-Date
  job4:
    runs-on: windows-latest
    steps:
      - needs: [job1, job2, job3]
        uses: actions/checkout@v3
        name: print date
        run: date
