name: disk space
on:
  workflow_dispatch:
  
jobs:
  macos_diskspace:
    runs-on: macos-latest
    
    steps:
      - name: df
        run: |
          df -h
          
  unbuntu_diskspace:
    runs-on: ubuntu-latest
    
    steps:
      - name: df
        run: |
          df -h
