# This is a basic workflow to help you get started with Actions

name: large_file_check

on:
  pull_request_target:
    branches:
      - main
      
jobs:
  check_lfs:
    runs_on: unbuntu-latest
    steps:
      - name: LFS-warning
        uses: ActionsDesk/lfs-warning@v3.2
        with:
          filesizelimit: 10mb
