---
on:
  push:
  
jobs:
  set-output-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: capture output
        run: |
          content="$(ls -l | tee /dev/fd/2)"
          content="${content//'%'/'%25'}"
          content="${content//$'\n'/'%0A'}"
          content="${content//$'\r'/'%0D'}"
          echo "::set-output name=ls::$content"
        id: ls
    outputs:
      ls_output: ${{ steps.ls.outputs.ls }}
  echo-output-test:
    runs-on: ubuntu-latest
    needs: set-output-test
    steps:
      - name: echo output
        run: |
          echo "${{ needs.set-output-test.outputs.ls_output }}"
