---
on:
  push:
  
jobs:
  set-output-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: capture output
        run: |
          echo "::set-output name=LS_OUTPUT::$(ls -l)"
        id: ls
      - name: echo output
        run: |
          LS_OUTPUT="${{ steps.ls.outputs.LS_OUTPUT }}"
          LS_OUTPUT="${LS_OUTPUT//'%'/'%25'}"
          LS_OUTPUT="${LS_OUTPUT//$'\n'/'%0A'}"
          LS_OUTPUT="${LS_OUTPUT//$'\r'/'%0D'}"
          echo "${LS_OUTPUT}"
