---
on:
  push:
  
jobs:
  set-output-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: capture output
        run: |
          echo 'LS_OUTPUT<<EOF' >> $GITHUB_ENV
          ls -l >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - name: echo output
        run: |
          echo "${LS_OUTPUT}"
