---
on:
  push:
  
jobs:
  set-output-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: capture output
        run: |
          echo "op<<EOF" >> $GITHUB_OUTPUT
          echo $(ls -l)" >> $GITHUB_OUTPUT
          echo "EOF">> $GITHUB_OUTPUT
        id: ls
    outputs:
      ls_output: steps.ls.outputs.op
  echo-output-test:
    runs-on: ubuntu-latest
    needs: set-output-test
    steps:
      - name: echo output
        run: |
          echo "${{ needs.set-output-test.outputs.ls_output }}"
