---
on:
  push:
  
jobs:
  set-output-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: capture output
        run: |
          content="$(ls -l | tee /dev/fd/2)"
          content="${content//'%'/'%25'}"
          content="${content//$'\n'/'%0A'}"
          content="${content//$'\r'/'%0D'}"
          echo "::set-output name=ls_output::$content"
        id: ls
  echo-output-test:
    runs-on: ubuntu-latest
    steps:
      - name: echo output
        run: |
          echo "${{ jobs.set-output-test.steps.ls.outputs.ls_output }}"
